CREATE TABLE ORDERS
(
    "ID"       NUMBER(11)   NOT NULL,
    AUTO_ID    NUMBER(11)   NOT NULL,
    STORAGE_ID NUMBER(11)   NOT NULL,
    PRODUCT_ID VARCHAR2(32) NOT NULL,
    COUNT      NUMBER(11),
    ADDRESS    VARCHAR2(128) DEFAULT 'CHINA',
    PRIMARY KEY ("ID", AUTO_ID)
);
CREATE SEQUENCE ORDER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE STORAGE
(
    "ID"       NUMBER(11)   NOT NULL,
    PRODUCT_ID VARCHAR2(32) NOT NULL,
    USED       NUMBER(11),
    PRIMARY KEY ("ID", PRODUCT_ID)
);

INSERT INTO STORAGE
VALUES (1, 'product-1', 0);
