// 
// Decompiled by Procyon v0.5.36
// 

package com.oceanbase.jdbc;

import java.sql.SQLException;
import com.oceanbase.jdbc.internal.util.exceptions.ExceptionFactory;

public class ClientSidePreparedStatement extends JDBC4PreparedStatement
{
    public ClientSidePreparedStatement(final OceanBaseConnection connection, final String sql, final int resultSetScrollType, final int resultSetConcurrency, final int autoGeneratedKeys, final ExceptionFactory exceptionFactory) throws SQLException {
        super(connection, sql, resultSetScrollType, resultSetConcurrency, autoGeneratedKeys, exceptionFactory);
    }
}
